### ISSUE TITLE
List supported boards (Mega?, Yún?, Micro?, Due? Zero?...) in README

### ISSUE THREAD

**Issue by q2dg** [adafruit/Adafruit_SleepyDog#2]
"Arduino" is too vague because the ecosystem is quite different.
Thanks!

**Comment by tdicola** [comment]
Great point, thanks for raising the issue.  Just updated the readme to clarify it's only for the Uno (ATmega328P) for now.  There isn't a lot of 328P-specific logic in the AVR code and it might work on other chips like the 32u4, but I haven't tried it to be sure yet.
