### ISSUE TITLE
Bricked 32U4

### ISSUE THREAD

**Issue by Thijxx** [adafruit/Adafruit_SleepyDog#34]
Uploaded the following sketch to my 32U4 and now it's bricked.

Does not initialize USB anymore, my computer never sees the chip.

```
#include <Adafruit_SleepyDog.h>

void setup() {
  pinMode(15, HIGH);
}

void loop() {
  int sleepMS = Watchdog.sleep(3000);
  #if defined(USBCON) && !defined(USE_TINYUSB)
    USBDevice.attach();
  #endif
digitalWrite(15, HIGH);
delay(500);
digitalWrite(15, LOW);
}
```

**Comment by ladyada** [comment]
we dont know what bootloader is on there, but it could be interfering? sorry we dont own one of these - you could ask the vendor you purchased from for tech support and help!
