### ISSUE TITLE
Update README.md to list ESP32-S3 Compatibility

### ISSUE THREAD

**Issue by ab-tools** [adafruit/Adafruit_SleepyDog#44]
ESP32-S2 is mentioned as compatible for this library.

Are there issues expected for ESP32-S3 based boards (like ESP32-S3-DevKitC-1-N32R8V) or is the compatibility for ESP32-S3 just missing in the compatibility list so far?

Thanks for clarification
Andreas

**Comment by brentru** [comment]
@ab-tools  I've used this library with ESP32-S3 before, updating this issue to reflect that the list needs to be updated via a PR.
